### ISSUE TITLE
Inference.lagda.md doesn't load

### ISSUE THREAD

**Issue by ShreckYe** [plfa/plfa.github.io#615]
I got the following error when trying to load "src/plfa/part2/Inference.lagda.md":

```text
/home/shreckye/GitProjects/plfa/src/plfa/part2/Inference.lagda.md:583,5-26
Could not parse the application ¬ ∃[ A ] (Γ ∋ x ⦂ A)
Operators used in the grammar:
  ¬    (prefix operator, level 3) [¬_ (/home/shreckye/GitProjects/agda-stdlib/src/Relation/Nullary.agda:26,1-3)]  
  ∃[_] (prefix notation, level 2) [∃-syntax (/home/shreckye/GitProjects/agda-stdlib/src/Data/Product.agda:80,1-9)]
when scope checking ¬ ∃[ A ] (Γ ∋ x ⦂ A)
```
It seems to be casused by `¬_` having higher precedence than `∃-syntax` and parentheses should be added.

**Comment by wadler** [comment]
I don't get the problem you report when loading on my machine. Do you have the version of Agda specified in "Getting Started"?

**Comment by ShreckYe** [comment]
Sorry about this. I just checked and I do have a different version of Agda. I have the latest Agda version 2.6.2, which is different from 2.6.1.3 specified in "Getting Started". My stdlib version is v1.6 as specified.

**Comment by wenkokke** [comment]
@ShreckYe Can you confirm this is resolved after switching to the correct Agda version?

**Comment by ShreckYe** [comment]
OK. I switched back to 2.6.1.3 and the problem is still there. I installed Agda using Cabal. Can this be why it happens?

**Comment by wenkokke** [comment]
I think I remember fixing a bunch of problems just like this a long time ago, when trying to upgrade to the most recent version of Agda. I think something did change in the standard library.

Apologies, the book is in a slight state of disrepair because I’ve been dealing with carpal tunnel for the past half year. In the meantime you can fix it locally by simply changing the parentheses.
